apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: symfony-restaurant-ingress
  namespace: symfony-restaurant
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:153806140965:certificate/41113cbc-e9c1-4895-b229-6b0839c7fe5d
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: symfony-restaurant-svc
                port:
                  number: 80
